import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TopNav />
        <main className="container mx-auto">{children}</main>
      </body>
    </html>
  );
}

function TopNav() {
  return (
    <div className="container  inset-0 mx-auto h-min w-full bg-transparent py-4 backdrop-blur-xl">
      <nav className="flex w-full items-center justify-center">Top Nav</nav>
    </div>
  );
}
